version: '3.8'

services:
  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "3001:3001" # Expose port for external access
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/inventorydb
    depends_on:
      - mongo
    networks:
      - microservices-network

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3002:3002" # Expose port for external access
    environment:
      - NODE_ENV=production
      - INVENTORY_SERVICE_URL=http://inventory-service:3001
      - MONGO_URI=mongodb://mongo:27017/orderdb
    depends_on:
      - inventory-service
      - mongo
    networks:
      - microservices-network

  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port for external access
    networks:
      - microservices-network

  # Redis (if needed for inter-service communication)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
