services:
  # Inventory Service
  inventory-service:
    build:
      context: ./src/services/inventory
      dockerfile: Dockerfile
    image: keenlabi/you-verify-assessment-inventory-service
    container_name: inventory-service
    ports:
      - "3002:3002" # Expose port for external access
    environment:
      - PORT=3002 
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/inventory-db
    depends_on:
      - mongo
    networks:
      - microservices-network

  # Order Service
  order-service:
    build:
      context: ./src/services/order
      dockerfile: Dockerfile
    image: keenlabi/you-verify-assessment-order-service
    container_name: order-service
    ports:
      - "3001:3001" # Expose port for external access
    environment:
      - PORT=3001
      - NODE_ENV=development
      - INVENTORY_SERVICE_URL=http://inventory-service:3001
      - MONGO_URI=mongodb://mongo:27017/order-db
    depends_on:
      - inventory-service
      - mongo
    networks:
      - microservices-network

  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port for external access
    networks:
      - microservices-network

  # Redis (if needed for inter-service communication)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
