# Base image
FROM node:21.7.3

# Set the working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the service code
COPY . .

# Change to the service's subdirectory
WORKDIR /usr/src/services/order

# Build the application
RUN npm run build

# Expose the port that the service runs on
EXPOSE 3001

# Run the application
CMD ["npm", "run", "start:prod"]
